# Generated by Django 2.2.9 on 2020-01-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_cell',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
