# Generated by Django 2.2.9 on 2020-01-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20200114_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
