# Generated by Django 2.2.9 on 2020-01-26 09:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entries',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='key value pair (time, entry) for each day'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('date', 'journal')},
        ),
    ]
