# Generated by Django 2.2.9 on 2020-01-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_auto_20200126_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.Journal'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journals.Profile'),
        ),
    ]
