# Generated by Django 2.2.9 on 2020-01-26 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_auto_20200126_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='primary_cell',
            field=models.CharField(default=1, max_length=10, verbose_name=django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')),
            preserve_default=False,
        ),
    ]
