# Generated by Django 2.2.9 on 2020-01-26 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_auto_20200126_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='primary_cell',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')]),
        ),
    ]
