# Generated by Django 2.2.9 on 2020-01-27 10:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_auto_20200126_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Maintains list of active and inactive todos')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journals.Profile')),
            ],
        ),
    ]
